name: clair3
channels:
  - bioconda
  - conda-forge
  - pkgs/main
dependencies:
  - autoconf
  - automake
  - cffi
  - libdeflate
  - parallel
  - python=3.11
  - zlib
  - numpy=1.26.4
  - whatshap
  - nanoplot
  - chopper
  - yq
  - pip:
    - torch==2.2.*
    - torchvision==0.17.*
    - torchaudio==2.2.*
